'use strict';
const modal = document.querySelector('.modal');
const overlay = document.querySelector('.overlay');
const btnCloseModal = document.querySelector('.close-modal');
const btnsOpenModal = document.querySelectorAll('.show-modal');


const openModal = function(){
    modal.classList.remove('hidden');
    overlay.classList.remove('hidden');
}

const closeModal = function(){
    modal.classList.add('hidden');
    overlay.classList.add('hidden');
}

for(let i = 0; i < btnsOpenModal.length; i++)
    btnsOpenModal[i].addEventListener('click', openModal);

btnCloseModal.addEventListener('click', closeModal);
overlay.addEventListener('click', closeModal);

// Today, We Will Learn How To Handle KeyPress Events,
// And Make Our Modal Window Close, When The Escape Key Is Pressed,
// So, In Order To Listen To Keyboard Events, We Still Need To Use addEventListener,
// Because The Keypress Event Is Simply Just An Event,
// Now Keyboard Events Are Also Called Global Events,
// Because They Dont Happen On One Specific Element,
// And For Global Events, Like Keyboard Events,
// We Ususally Listen On The Whole Document,
// Also, I Wrote This Comment Below The Code Above,
// Since What We're Gonna Be Working On Is Below This😅,
// So Now Lets Write Our document And Everything,

document.addEventListener('keydown', function(e){
    // console.log('A key was pressed');
    console.log(e.key);

// Now Let Me Explain, After The Event Listener, We Write The Event Name As Always,
// And There Are 3 Types Of Events For The Keyboard,
// The Keydown, Keypress, And Keyup,
// You Can Search About It On Google To Find Out What Each Do,
// But Right Now, We Use Keydown, Which Is The Most Used One,
// Then We Specify Our Function As Always,
// Now, If We Press Any Key, It Will Print The Message In The Console,
// With A Number On The Side, So, Whenever We Press A Key,
// A Keydown Event Is Generated, And Our Handler Function,
// Is Waiting For That Event To Happen,
// And Anytime That An Event Like This Occurs,
// JavaScript Will Generate An Object, Which Contains All The Information,
// About The Event Itself, And We Can Access That Object In The Event Handler Function,
// No Up Until This Point, We Never Looked At That Event,
// And Just Listened For It, Then Reacted To It,
// But This Time, We Need To Look At The Event Object,
// In Order To Figure Out Which Key Was Pressed,
// First, We Give The Function A Parameter, So I Have Called It e AKA Event,
// Then Do console.log(e), And Now We Get This KeyboardEvent In The Console,
// Which Is Just An Object Generated By JavaScript, And It Says Which Key Was Pressed,
// So Like Hitting Enter, Would Make One, Same With Escape, Backspace, ETC,
// And Since We Were Getting It From The Key Property, Lets Use It, So .key,
// Now If We Press Any Key, It Will Only Show That Key In The Console,
// So Now, Because I Know This Was Pressed, We Can Use It,
// To Close The Modal Window, When The Escape Key Is Pressed,
// So Lets Use An If-Else Statement,
//   if(e.key === 'Escape') {
//     // console.log('Esc was pressed');
//     if(!modal.classList.contains('hidden')) {
//         closeModal();

//     }
//   }
// });

if(e.key === 'Escape' && !modal.classList.contains('hidden')) {
    // console.log('Esc was pressed');
    closeModal();


}
});

// After This, We Need It To See If The Modal Is Visible,
// And We Can Use Classes To Do So,
// So When The Modal Has The Class Hidden, Means Its Invisible,
// And If Not, Then Its Visible, And Thats The Condition When We Want To Close It,
// So, We Will Check If The Element Has The Class,
// Now, We Simply Use The modal.classList, WITH The !,
// Which Is Slowly Becoming, Very Important As You Can See,
// But This Is The More Detailed And Long Way, But We Can Make This Shorter,
// So By Using "&&" Which Allows Us To Remove The 2nd if,

// So, Everything Works Perfectly Now, And That Was Pretty Much It,
// This Was The 3rd, And Last Part Of This Project,
// Yes Indeed😄, This Wasnt Very Long, But This Was Actually A Pretty Useful Project,
// And By That, I Mean This Contained Lots Of Important Stuff,
// But This Was Also One Of The More Confusing Projects We've Done,
// Well If I Was A Beginner, It Would Be For Me Atleast😅,
// Now, I Would, Again, Like To Congratulate You For Making This Far👏,
// For Completeing These Two Projects With Me, And Hopefully, Doing The Challenges,
// But, There Is One More Project Left In This Section, And I Will See You There,
// In The Meantime, Keep Practicing, Keep Analyzing And Researching,
// And Happy Coding🚀!




