'use strict';
// Welcome...To The First Subrepo Of This Section😄!
// In Which We Will Create Our First Project🫡!
// And You Can See By The Name, We Will Create A Game,
// In Which We Will Guess A Certain Number,
// With More Details, And After This We Will Learn More About DOM,
// Also I Made The Main Page Of The Project Already,
// Because Of The HTML And CSS Files Of Course,
// And Used A Retro/80's Design For It😁,
// Also, If You Dont Know Anything About HTML Or CSS,
// Then You Must Watch And Learn The Super Main Basics Of It,
// And You Can Do So, By Watching Some Crash Course On Youtube,
// Or Any Other Platforms You Can Find Them On To Learn,
// But Now, Let's Begin,

// Here In This Line, We Use document.querySelector To Select The Class Name,
// Which Is In The HTML File, And The Class Name Is Message,
// And If You Dont Understand This, Than That Is Literally,
// Exactly Why I Want You To Watch And Learn HTML And CSS From Some Crash Course😅,
console.log(document.querySelector('.message').textContent);
// Now We Run Live-Server, Which I Recommend You Using,
// And In The Console, We See The Text Content Of The Class Message,
// Which Is "Start Guessing...", But We Only Want It To Show The Text,
// Thats Why We Used ".textContent",
// Also This Is The First DOM Manipulation That You Did👏!

// Now Because Most Of You Will Still Not Understand Most Of This,
// And I'm Talking About The DOM And DOM Manipulation,
// And To Clear That Confusion, I Will Divide This Project Into Many Smaller Parts,
// So In Different Subrepos, Which Was Not What I Originally Planned😑,
// But This Just Means A Simpler And Easier To Understand Concept For You😉,
// So, In The Next Subrepo, We Will Learn About Selecting And Manipulating Elements,